version: '2'
services:
    resto-app:
        image: resto
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://resto-postgresql:5432/Resto
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    resto-postgresql:
        extends:
            file: postgresql.yml
            service: resto-postgresql
